### ISSUE TITLE
Suggestion: generate progressive JPEGs

### ISSUE THREAD

**Issue by asgerb** [tomasc/dragonfly_libvips#7]
Hi @tomasc,

Looking into performance/speed/compression it seems that progressive JPEGs are preferred ([here](https://images.guide/), [here](https://optimus.keycdn.com/support/progressive-jpeg/) or [here](https://www.hostinger.com/tutorials/website/improving-website-performance-using-progressive-jpeg-images#gref)).

Currently the thumbnail processor does not generate progressive JPEGs and I'm wondering if this might not be a useful addition? Could also be a new processor, but since it's only for JPEGs I'm not sure how to implement that.

It unfortunately seems that vips' `.thumbnail` method does not support "interlacing" (progressive), but it can be done with the `.jpegsave` method: https://github.com/jcupitt/ruby-vips/blob/428d5c106fb4a64521159c6b0c4f9391eea2eba6/lib/vips/methods.rb#L1333

Let me know your thoughts and I can try and take a stab at this 🙂

**Comment by tomasc** [comment]
Hi @asgerb I am up for this.
Ideally as an `output_option` (`progressive: true`?) that is applied only in case the output format is `jpg`. (We already implement autorotate in similar way – see https://github.com/tomasc/dragonfly_libvips/blob/master/lib/dragonfly_libvips/processors/encode.rb#L27-L29)
Please feel free to submit PR, thanks!
T

**Comment by tomasc** [comment]
resolved by #8
